site_name: Siddhi IO Kafka
site_description: Siddhi IO Kafka Extension
site_author: WSO2
site_url: https://wso2-extensions.github.io/siddhi-io-kafka/
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
repo_name: Siddhi-IO-Kafka
repo_url: https://github.com/wso2-extensions/siddhi-io-kafka
copyright: Copyright &copy; 2011 - 2018 WSO2
theme:
  name: material
  logo: images/siddhi-logo-w.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
extra:
  social:
  - type: github
    link: https://github.com/wso2/siddhi
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
markdown_extensions:
- admonition
- toc(permalink=true)
- codehilite(guess_lang=false)
pages:
- Welcome: index.md
- API Docs:
  - 5.0.1: api/5.0.1.md
  - 5.0.0: api/5.0.0.md
  - 4.2.1: api/4.2.1.md
  - 4.2.0: api/4.2.0.md
  - 4.1.21: api/4.1.21.md
  - 4.1.20: api/4.1.20.md
  - 4.1.19: api/4.1.19.md
  - 4.1.18: api/4.1.18.md
  - 4.1.17: api/4.1.17.md
  - 4.1.16: api/4.1.16.md
  - 4.1.15: api/4.1.15.md
  - 4.1.14: api/4.1.14.md
  - 4.1.13: api/4.1.13.md
  - 4.1.12: api/4.1.12.md
  - 4.1.11: api/4.1.11.md
  - 4.1.10: api/4.1.10.md
  - 4.1.9: api/4.1.9.md
  - 4.1.8: api/4.1.8.md
  - 4.1.7: api/4.1.7.md
  - 4.1.6: api/4.1.6.md
  - 4.1.5: api/4.1.5.md
  - 4.1.4: api/4.1.4.md
  - 4.1.3: api/4.1.3.md
  - 4.1.2: api/4.1.2.md
  - 4.1.1: api/4.1.1.md
  - 4.1.0: api/4.1.0.md
  - 4.0.17: api/4.0.17.md
  - 4.0.16: api/4.0.16.md
  - 4.0.15: api/4.0.15.md
  - 4.0.14: api/4.0.14.md
  - 4.0.13: api/4.0.13.md
  - 4.0.12: api/4.0.12.md
  - 4.0.11: api/4.0.11.md
  - 4.0.10: api/4.0.10.md
  - 4.0.9: api/4.0.9.md
  - 4.0.8: api/4.0.8.md
  - 4.0.7: api/4.0.7.md
  - latest: api/latest.md
- License: license.md
